[project]
name = "deep-learning-with-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "keras>=3.8.0",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "tensorflow>=2.18.0",
]
